#!/bin/bash
#
# run-test-evgen.sh -- regression tests for SatPlan/evgen.sh, the plan-recognition
# evidence generator.
#
# Behavioral, not gold diffs: the fixture problem is generated by ppgen.sh from a
# fixed seed and solved by planner.sh, so what is asserted is the relationship
# between the solution and the evidence -- the emitted literals are exactly the
# true ones at the requested slices, negatives complete the partition, and the
# file actually binds when handed back to the planner.
#
# That last one matters most.  Slice-pinned evidence fails SILENTLY downstream:
# an out-of-range slice or a misspelled predicate becomes a fresh unconstrained
# atom and the planner returns its UNCONDITIONED answer, no error.  So the suite
# checks not only that evgen refuses to write such a literal, but that a correct
# file changes the answer when it should.
#
# Run from anywhere:  bash tests/run-test-evgen.sh
# The cases that solve need a MaxSAT solver and skip cleanly without one.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd -P)"
export FIFO_LISP="${FIFO_LISP:-$REPO/lisp}"
EVGEN="$REPO/SatPlan/evgen.sh"
PPGEN="$REPO/SatPlan/ppgen.sh"
export REPO
PLANNER="$REPO/bin/planner.sh"
DOMAIN="$REPO/SatPlan/clara-logistics.pddl"
SOLVER="${WEIGHTED_SOLVER:-EvalMaxSAT_bin}"
TMP="$(mktemp -d)"; TMP="$(cd "$TMP" && pwd -P)"
trap 'rm -rf "$TMP"' EXIT

command -v sbcl >/dev/null 2>&1 || { echo "sbcl not found on PATH" >&2; exit 2; }

PASS=0; FAIL=0
name() { printf '  %-56s ... ' "$1"; }
pass() { echo "PASS"; PASS=$((PASS+1)); }
fail() { echo "FAIL ($1)"; FAIL=$((FAIL+1)); }
pycheck() { python3 - "$@"; }

# SRC is set below, after the fixture is solved; every case reads that snapshot
# rather than the live <problem>.answer, which planner.sh overwrites.
ev()    { bash "$EVGEN" --problem "$PROB" --domain "$DOMAIN" --solution "$SRC" "$@" 2>/dev/null; }
everr() { bash "$EVGEN" --problem "$PROB" --domain "$DOMAIN" --solution "$SRC" "$@" 2>&1 >/dev/null \
            | grep -v 'STYLE-WARNING\|^;\|^$' | tr '\n' ' '; }

# ---------------------------------------------------------------- fixture ---

PROB="$TMP/pb.pddl"
bash "$PPGEN" --style clique --clique-size 3 --number-cliques 2 --packages 3 \
     --trucks 2 --airplanes 1 --preferences 1 6 --goals-per-package 2 1 \
     --seed 23 -o "$PROB" 2>/dev/null
ANSWER="$TMP/pb.answer"

if command -v "$SOLVER" >/dev/null 2>&1; then
  WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$PROB" --domain "$DOMAIN" \
      --maxslices 12 >"$TMP/plan.log" 2>&1
fi
if [[ ! -f "$ANSWER" ]]; then
  echo "  (skipping: could not solve the fixture problem -- no MaxSAT solver '$SOLVER'?)"
  echo
  echo "=== summary: 0 passed, 0 failed (skipped) ==="
  exit 0
fi
# planner.sh rewrites <problem>.answer on every run, and the binding cases below
# run it WITH evidence -- so keep a pristine copy and generate from that, or a
# later case silently observes an earlier case's conditioned plan.
SRC="$TMP/pb-source.answer"; cp "$ANSWER" "$SRC"
HORIZON=$(grep -oE '\) [0-9]+\)$' "$SRC" | grep -oE '[0-9]+' | sort -n | tail -1)
BASE_COST=$(grep -oE '\(\*OBJECTIVE\* [0-9]+\)' "$SRC" | grep -oE '[0-9]+')

echo "=== evgen.sh (fixture: horizon $HORIZON, cost $BASE_COST) ==="

# ------------------------------------------------------------ positives ----

name "emits exactly the true literals at the requested slices"
ev --evidence "$TMP/a.txt" --slices "1-3,5" >/dev/null
if pycheck "$SRC" "$TMP/a.txt" <<'EOF'
import sys,re
ans=open(sys.argv[1]).read(); ev=open(sys.argv[2]).read()
want=set()
for kind,term,s in re.findall(r'\((HOLDS|OCCURS) (\([^)]*\)) (\d+)\)',ans):
    if int(s) in (1,2,3,5): want.add((kind.lower(),term.lower(),s))
got=set()
for kind,term,s in re.findall(r'^\((holds|occurs) (\([^)]*\)) (\d+)\)',ev,re.M):
    got.add((kind,term,s))
assert got==want, ("missing",sorted(want-got)[:3],"extra",sorted(got-want)[:3])
assert got, "nothing emitted"
EOF
then pass; else fail "positives do not match the solution"; fi

name "only the requested slices appear"
if pycheck "$TMP/a.txt" <<'EOF'
import sys,re
ev=open(sys.argv[1]).read()
sl={int(s) for s in re.findall(r'^\((?:holds|occurs) \([^)]*\) (\d+)\)',ev,re.M)}
assert sl=={1,2,3,5}, sl
EOF
then pass; else fail "wrong slices"; fi

name "a single slice, and a range, agree with the union of both"
ev --evidence "$TMP/s1.txt" --slices "2" >/dev/null
ev --evidence "$TMP/s2.txt" --slices "3" >/dev/null
ev --evidence "$TMP/s12.txt" --slices "2-3" >/dev/null
if [[ "$(grep -c '^(' "$TMP/s1.txt")" -gt 0 ]] && \
   [[ $(( $(grep -c '^(' "$TMP/s1.txt") + $(grep -c '^(' "$TMP/s2.txt") )) \
      -eq "$(grep -c '^(' "$TMP/s12.txt")" ]]
then pass; else fail "a range is not the union of its slices"; fi

# -------------------------------------------------------------- observe ----

name "--observe restricts to those fluent and action names"
ev --evidence "$TMP/o.txt" --slices "2-4" --observe "fly,in" >/dev/null
if pycheck "$TMP/o.txt" <<'EOF'
import sys,re
ev=open(sys.argv[1]).read()
heads={t.split()[0].lstrip('(') for t in
       re.findall(r'^\((?:holds|occurs) (\([^)]*\)) \d+\)',ev,re.M)}
assert heads<= {'fly','in'} and heads, heads
EOF
then pass; else fail "restriction wrong"; fi

name "--observe mixes a fluent name and an action name"
if grep -q '^(holds (in ' "$TMP/o.txt" && grep -q '^(occurs (fly ' "$TMP/o.txt"
then pass; else fail "the spec's \"fly,in\" case lost one of the two"; fi

name "no --observe means no restriction"
if pycheck "$TMP/a.txt" <<'EOF'
import sys,re
heads={t.split()[0].lstrip('(') for t in
       re.findall(r'^\((?:holds|occurs) (\([^)]*\)) \d+\)',open(sys.argv[1]).read(),re.M)}
assert len(heads)>2, heads
EOF
then pass; else fail "unrestricted run looks restricted"; fi

# --------------------------------------------------------- slice ranges ----

name "the last slice yields fluents but no actions"
ev --evidence "$TMP/last.txt" --slices "$HORIZON" >/dev/null
if [[ "$(grep -c '^(holds' "$TMP/last.txt")" -gt 0 && \
      "$(grep -c '^(occurs' "$TMP/last.txt" || true)" -eq 0 ]]
then pass; else fail "actions run 1..N-1, so slice N should have none"; fi

name "the last slice has no actions under --negative-evidence either"
# The positives-only case cannot see this: nothing is true at slice N anyway, so
# an emitter that forgot the actslices bound would look identical.  Negatives
# make it visible -- every ground action would show up as (not (occurs ... N)).
ev --evidence "$TMP/lastn.txt" --slices "$HORIZON" --negative-evidence 1 >/dev/null
if [[ "$(grep -c 'occurs' "$TMP/lastn.txt" || true)" -eq 0 && \
      "$(grep -c '^(not (holds' "$TMP/lastn.txt")" -gt 0 ]]
then pass; else fail "actions appeared at slice N (actions run 1..N-1)"; fi

name "the slice before it has both"
ev --evidence "$TMP/prev.txt" --slices "$((HORIZON-1))" >/dev/null
if [[ "$(grep -c '^(holds' "$TMP/prev.txt")" -gt 0 && \
      "$(grep -c '^(occurs' "$TMP/prev.txt")" -gt 0 ]]
then pass; else fail "slice N-1 should carry actions"; fi

# ---------------------------------------------------- negative evidence ----

name "--negative-evidence partitions the restricted universe exactly"
ev --evidence "$TMP/n.txt" --slices "3" --observe "in,fly" --negative-evidence 1 >/dev/null
if pycheck "$TMP/n.txt" "$SRC" <<'EOF'
import sys,re
ev=open(sys.argv[1]).read(); ans=open(sys.argv[2]).read()
pos={(k,t) for k,t,s in re.findall(r'^\((holds|occurs) (\([^)]*\)) (\d+)\)',ev,re.M)}
neg={(k,t) for k,t,s in re.findall(r'^\(not \((holds|occurs) (\([^)]*\)) (\d+)\)\)',ev,re.M)}
assert pos and neg, (len(pos),len(neg))
assert not (pos & neg), "an atom appears with both polarities"
# every positive is true in the solution, every negative is not
true={(k.lower(),t.lower()) for k,t,s in
      re.findall(r'\((HOLDS|OCCURS) (\([^)]*\)) (\d+)\)',ans) if s=='3'}
assert pos <= true, sorted(pos-true)[:3]
assert not (neg & true), sorted(neg & true)[:3]
EOF
then pass; else fail "positives and negatives do not partition cleanly"; fi

name "--negative-evidence unrestricted covers the whole universe"
ev --evidence "$TMP/nu.txt" --slices "3" --negative-evidence 1 >/dev/null
# the universe at one slice is every ground fluent plus every ground action
if [[ "$(grep -c '^(' "$TMP/nu.txt")" -gt $(( $(grep -c '^(' "$TMP/n.txt") * 5 )) ]]
then pass; else fail "unrestricted negatives are not much larger than the restricted ones"; fi

name "--negative-evidence 0 is the default and emits no negatives"
if ! grep -q '^(not ' "$TMP/a.txt"; then pass
else fail "negatives appeared without the flag"; fi

# ------------------------------------------------------- recorded header ---

name "the header records every setting, defaults included"
if pycheck "$TMP/a.txt" <<'EOF'
import sys,re
p=dict(re.findall(r'^;;   (--[\w-]+) (.+)$',open(sys.argv[1]).read(),re.M))
for f in ('--problem','--evidence','--solution','--domain','--slices',
          '--observe','--negative-evidence'):
    assert f in p, (f,p)
assert p['--slices']=='1-3,5' and p['--negative-evidence']=='0' and p['--observe']=='""'
EOF
then pass; else fail "settings block incomplete"; fi

name "the header names the solution horizon and the literal count"
if grep -qE "^;; Solution horizon: $HORIZON slices \(fluents 1-$HORIZON, actions 1-$((HORIZON-1))\); [0-9]+ literals\.$" "$TMP/a.txt"
then pass; else fail "$(grep '^;; Solution' "$TMP/a.txt")"; fi

name "the recorded settings block replays byte for byte"
RT_BAD=""
for spec in "--slices 1-3,5" \
            "--slices 2-4 --observe fly,in" \
            "--slices 3 --observe in,fly --negative-evidence 1"; do
  ev --evidence "$TMP/rt.txt" $spec >/dev/null
  cp "$TMP/rt.txt" "$TMP/rt-orig.txt"
  # feed the file's own header back in as the command line; it names --evidence,
  # so this rewrites the same file and must reproduce it exactly
  eval "bash '$EVGEN' $(sed -n 's/^;;   //p' "$TMP/rt.txt" | tr '\n' ' ')" 2>/dev/null
  diff -q "$TMP/rt-orig.txt" "$TMP/rt.txt" >/dev/null || { RT_BAD="$spec"; break; }
done
if [[ -z "$RT_BAD" ]]; then pass; else fail "did not replay: $RT_BAD"; fi

# ------------------------------------------------------------ defaults -----

name "--solution defaults to <problem>.answer"
bash "$EVGEN" --problem "$PROB" --domain "$DOMAIN" \
     --evidence "$TMP/d.txt" --slices "2" >/dev/null 2>&1
if grep -q ";;   --solution .*pb\.answer$" "$TMP/d.txt"; then pass
else fail "default solution path wrong"; fi

name "--domain defaults to the problem's own (:domain ...)"
cp "$DOMAIN" "$TMP/clara-logistics.pddl"
if bash "$EVGEN" --problem "$PROB" --evidence "$TMP/dd.txt" --slices "2" 2>/dev/null \
   && grep -q '^(holds' "$TMP/dd.txt"
then pass; else fail "did not resolve the domain beside the problem"; fi

# -------------------------------------------------------------- binding ----

name "the evidence binds: the true observations reproduce the plan's cost"
run_cost() {  # run_cost <evidence-file>
  WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$PROB" --domain "$DOMAIN" \
      --numslices "$HORIZON" --evidence-file "$1" 2>&1 \
    | grep -oE 'cost [0-9]+' | tail -1 | grep -oE '[0-9]+'
}
if [[ "$(run_cost "$TMP/a.txt")" == "$BASE_COST" ]]; then pass
else fail "conditioning on the real plan changed its cost"; fi

name "the evidence binds: a shifted observation costs more"
# move one observed action to a different slice; the plan must now work around it
python3 - "$TMP/o.txt" "$TMP/bad.txt" <<'EOF'
import sys,re
t=open(sys.argv[1]).read()
m=re.search(r'^\(occurs (\([^)]*\)) (\d+)\)$',t,re.M)
assert m, "fixture has no observed action to shift"
t=t.replace(m.group(0), "(occurs %s 1)" % m.group(1), 1)
open(sys.argv[2],'w').write(t)
EOF
BAD_COST="$(run_cost "$TMP/bad.txt")"
if [[ -n "$BAD_COST" && "$BAD_COST" -gt "$BASE_COST" ]]; then pass
else fail "shifted observation gave cost '$BAD_COST' vs base $BASE_COST"; fi

# ---------------------------------------------------- recognition mode -----

echo
echo "=== --recognition (for bin/recognize.sh) ==="

name "--recognition 1 emits exactly ONE form"
ev --evidence "$TMP/r.txt" --slices "1-3" --observe "drive,fly,load" --recognition 1 >/dev/null
NF=$(sbcl --noinform --non-interactive --eval "(let ((*read-eval* nil) (n 0))
       (with-open-file (i \"$TMP/r.txt\") (loop for f = (read i nil :eof) until (eq f :eof) do (incf n)))
       (princ n))" 2>/dev/null | tr -dc '0-9')
# one form is the whole requirement: recognize.sh negates the file by wrapping
# its contents in (not ...), and (not A B) is not a formula
if [[ "$NF" == "1" ]] && grep -q '^(and$' "$TMP/r.txt"; then pass
else fail "$NF top-level form(s)"; fi

name "the default is still one literal per line"
ev --evidence "$TMP/rd.txt" --slices "1-3" --observe "drive,fly,load" >/dev/null
NF=$(sbcl --noinform --non-interactive --eval "(let ((*read-eval* nil) (n 0))
       (with-open-file (i \"$TMP/rd.txt\") (loop for f = (read i nil :eof) until (eq f :eof) do (incf n)))
       (princ n))" 2>/dev/null | tr -dc '0-9')
if [[ "$NF" -gt 1 ]] && ! grep -q '^(and$' "$TMP/rd.txt"; then pass
else fail "default mode changed shape ($NF forms)"; fi

name "--recognition carries the same literals as the default"
if pycheck "$TMP/r.txt" "$TMP/rd.txt" <<'EOF'
import sys,re
a=open(sys.argv[1]).read(); b=open(sys.argv[2]).read()
lit=lambda t: sorted(re.findall(r'\((?:holds|occurs) \([^)]*\) \d+\)',t))
assert lit(a)==lit(b) and lit(a), (len(lit(a)),len(lit(b)))
EOF
then pass; else fail "the two modes disagree on content"; fi

name "--recognition never emits a derived predicate"
# Free by construction: evgen emits from the FLUENTS domain, and derived
# predicates are deliberately kept out of it -- so a hypI hypothesis predicate,
# which is derived, can never leak into the observations it is meant to infer.
if ! grep -qiE '\(holds \((hyp|clear-d|spells)' "$TMP/r.txt"; then pass
else fail "a derived predicate reached the evidence"; fi

name "--recognition 1 with --negative-evidence 1 is refused"
if everr --evidence "$TMP/x.txt" --slices "2" --recognition 1 --negative-evidence 1 \
   | grep -q "do not go together"; then pass
else fail "should refuse complete observability in recognition mode"; fi

name "--recognition 2 is refused"
if everr --evidence "$TMP/x.txt" --slices "2" --recognition 2 | grep -q "must be 0 or 1"
then pass; else fail "should reject a non-boolean"; fi

name "the recognition header replays byte for byte"
cp "$TMP/r.txt" "$TMP/r-orig.txt"
eval "bash '$EVGEN' $(sed -n 's/^;;   //p' "$TMP/r.txt" | tr '\n' ' ')" 2>/dev/null
if diff -q "$TMP/r-orig.txt" "$TMP/r.txt" >/dev/null; then pass
else fail "did not replay"; fi

name "recognize.sh's negation of it is a valid formula"
# The mechanism, without the 3n planner runs a full recognize.sh does: comply
# must reproduce the plan's cost, not-comply must differ.
{ echo "(not"; grep -v '^[[:space:]]*;;' "$TMP/r.txt"; echo ")"; } > "$TMP/rneg.txt"
CO="$(run_cost "$TMP/r.txt")"
CN="$(run_cost "$TMP/rneg.txt")"
if [[ "$CO" == "$BASE_COST" && -n "$CN" && "$CN" != "$CO" ]]; then pass
else fail "c(O)=$CO (want $BASE_COST), c(notO)=$CN"; fi

name "and the not-comply case is the more expensive one"
# c(notO) > c(O) is what makes this hypothesis' likelihood exceed one half.
if [[ "$CN" -gt "$CO" ]]; then pass
else fail "c(notO)=$CN is not above c(O)=$CO"; fi

# --------------------------------------------------- recognize.sh guards ---
# The full pipeline is 3n planner runs, far too slow for a suite; these are the
# fast guards that decide whether an evidence file is usable at all.

echo
echo "=== bin/recognize.sh, FiFO evidence ==="
RECOGNIZE="$REPO/bin/recognize.sh"
RPROB="$REPO/SatPlan/Examples/Plan_Recognition/IntrusionDetectionCosts/problem.pddl"
RDOM="$REPO/SatPlan/Examples/Plan_Recognition/IntrusionDetectionCosts/intrusion-detection-costs.pddl"

name "a multi-form evidence file is refused, with the fix named"
# The not-comply case is (not <the file>), and (not A B) is not a formula.
if bash "$RECOGNIZE" "$RDOM" "$RPROB" "$TMP/rd.txt" --evidence-kind fifo \
     --out "$TMP/rg" 2>&1 >/dev/null | grep -q "must hold exactly one"; then pass
else fail "accepted a file it cannot negate"; fi

name "the refusal points at --recognition 1"
if bash "$RECOGNIZE" "$RDOM" "$RPROB" "$TMP/rd.txt" --evidence-kind fifo \
     --out "$TMP/rg" 2>&1 >/dev/null | grep -q -- "--recognition 1"; then pass
else fail "the message does not say how to fix it"; fi

# The guard must also NOT reject valid input.  A full run is 3n planner calls, so
# start one and stop it as soon as it has passed the guard and settled a horizon.
run_until_horizon() {   # run_until_horizon <log> <extra args>...
  local log="$1"; shift
  bash "$RECOGNIZE" "$RDOM" "$RPROB" "$TMP/r.txt" --evidence-kind fifo \
       --out "$TMP/rg2" "$@" >"$log" 2>&1 &
  local pid=$!
  local i
  for i in $(seq 1 120); do
    grep -q "Horizon H =" "$log" 2>/dev/null && break
    kill -0 "$pid" 2>/dev/null || break
    sleep 0.5
  done
  pkill -P "$pid" 2>/dev/null; kill "$pid" 2>/dev/null; wait "$pid" 2>/dev/null
}

name "a single-form file gets past that guard"
run_until_horizon "$TMP/rg2.log" --horizon 6
if grep -q "Horizon H =" "$TMP/rg2.log" \
   && ! grep -q "must hold exactly one" "$TMP/rg2.log"; then pass
else fail "rejected a single (and ...) form"; head -3 "$TMP/rg2.log" | sed 's/^/      | /'; fi

name "the horizon is raised to the largest slice observed"
# Slice-pinned evidence cannot hold at a shorter horizon: every c(O) would come
# back infinite and every posterior 0.
MAXOBS=$(grep -oE '\) [0-9]+\)' "$TMP/r.txt" | grep -oE '[0-9]+' | sort -n | tail -1)
run_until_horizon "$TMP/rg3.log" --horizon 1
if grep -q "Raising horizon 1 -> $MAXOBS" "$TMP/rg3.log" \
   && grep -q "Horizon H = $MAXOBS" "$TMP/rg3.log"; then pass
else fail "did not raise the horizon to $MAXOBS"; head -3 "$TMP/rg3.log" | sed 's/^/      | /'; fi

name "an unknown --evidence-kind is refused"
if bash "$RECOGNIZE" "$RDOM" "$RPROB" "$TMP/r.txt" --evidence-kind lisp \
     --out "$TMP/rg" 2>&1 >/dev/null | grep -q "must be 'pddl' or 'fifo'"; then pass
else fail "accepted an unknown evidence kind"; fi

# ------------------------------------------------------ dataset export -----
# The R&G dataset format, for handing an instance to a tool chain that does not
# read FiFO.  The fixture is IntrusionDetectionCosts, whose SOURCE dataset is
# also checked in -- so the export can be checked against published ground truth,
# not just against itself.

echo
echo "=== --export-dataset (R&G format) ==="
PR="$REPO/SatPlan/Examples/Plan_Recognition"
RCPROB="$PR/IntrusionDetectionCosts/problem.pddl"
RCDOM="$PR/IntrusionDetectionCosts/intrusion-detection-costs.pddl"
DS="$TMP/ds"

# A plan to observe.  Solve ONE hypothesis rather than the disjunctive problem:
# its cheapest plan is hyp0, which is 20 actions and needs a 21-slice horizon to
# re-check.  The export still runs against the disjunctive problem, since that is
# what carries the hypothesis set.
cp "$RCPROB" "$RCDOM" "$TMP/"
sbcl --noinform --non-interactive --eval "(let* ((*read-eval* nil)
     (p (with-open-file (i \"$TMP/problem.pddl\") (read i))))
   (with-open-file (o \"$TMP/sg.pddl\" :direction :output :if-exists :supersede)
     (let ((*print-case* :downcase))
       (print (mapcar (lambda (s)
                        (if (and (consp s) (symbolp (first s))
                                 (string-equal (symbol-name (first s)) \"GOAL\"))
                            (list :goal (list (intern \"HYP3\"))) s))
                      p) o))))" >/dev/null 2>&1
RSOLVED=0
if WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$TMP/sg.pddl" \
     --domain "$TMP/intrusion-detection-costs.pddl" --maxslices 8 \
     >"$TMP/rc.log" 2>&1 && [[ -f "$TMP/sg.answer" ]]; then RSOLVED=1; fi

if [[ "$RSOLVED" -eq 1 ]]; then
  bash "$EVGEN" --problem "$TMP/problem.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "1-3" --export-dataset "$DS" >/dev/null 2>&1

  name "writes the five dataset files plus a README"
  MISSING=""
  for f in domain.pddl template.pddl hyps.dat obs.dat real_hyp.dat README.md; do
    [[ -s "$DS/$f" ]] || MISSING="$MISSING $f"
  done
  if [[ -z "$MISSING" ]]; then pass; else fail "missing:$MISSING"; fi

  name "hyps.dat matches the PUBLISHED dataset, hypothesis for hypothesis"
  # Content, not bytes: the two checked-in datasets already disagree on case and
  # on whether a space follows the comma, and parse-hyps is blind to both.
  if pycheck "$PR/IntrusionDetection/hyps.dat" "$DS/hyps.dat" <<'EOF'
import sys,re
def norm(p):
    out=[]
    for line in open(p):
        line=line.strip()
        if line: out.append([a.strip().lower() for a in line.split(',')])
    return out
a,b=norm(sys.argv[1]),norm(sys.argv[2])
assert a==b, (len(a),len(b),[x for x in a if x not in b][:2])
EOF
  then pass; else fail "hypotheses differ from the published hyps.dat"; fi

  name "hyps.dat is ordered by the problem's goal disjunction"
  if pycheck "$RCDOM" "$RCPROB" "$DS/hyps.dat" <<'EOF'
import sys,re
dom=open(sys.argv[1]).read(); prob=open(sys.argv[2]).read()
order=re.findall(r'\((hyp\d+)\)',prob.split('(:goal')[1])
rules=dict((m.group(1),m.group(2)) for m in
           re.finditer(r'\(:derived \((hyp\d+)\)\s*(\(and.*?\)\)|\(\w[^()]*\))',dom,re.S))
lines=[l.strip() for l in open(sys.argv[3]) if l.strip()]
assert len(lines)==len(order), (len(lines),len(order))
for name,line in zip(order,lines):
    atoms=[a.strip().lower() for a in line.split(',')]
    body=re.findall(r'\([\w-]+ [\w-]+\)',rules[name].lower())
    assert atoms==body, (name,atoms,body)
EOF
  then pass; else fail "hyps.dat order or content wrong"; fi

  name "obs.dat is the plan's actions at the requested slices, in order"
  if pycheck "$TMP/sg.answer" "$DS/obs.dat" <<'EOF'
import sys,re
ans=open(sys.argv[1]).read()
want=[(int(s),t.lower()) for t,s in
      re.findall(r'\(OCCURS (\([^)]*\)) (\d+)\)',ans) if int(s) in (1,2,3)]
got=[l.strip().lower() for l in open(sys.argv[2]) if l.strip()]
assert sorted(got)==sorted(t for _,t in want), (len(got),len(want))
# slice order preserved (within a slice any order is allowed: slices are parallel)
seen=[]
for line in got:
    seen.append(min(s for s,t in want if t==line))
assert seen==sorted(seen), seen
EOF
  then pass; else fail "obs.dat wrong"; fi

  name "real_hyp.dat is the hypothesis the plan achieved, and is in hyps.dat"
  if pycheck "$TMP/sg.answer" "$DS/hyps.dat" "$DS/real_hyp.dat" <<'EOF'
import sys,re
hyp=re.findall(r'\(HOLDS \((HYP\d+)\) \d+\)',open(sys.argv[1]).read())
assert hyp, "the answer names no hypothesis"
i=int(hyp[0][3:])                                  # hypN -> N, the hyps.dat index
lines=[[a.strip().lower() for a in l.split(',')] for l in open(sys.argv[2]) if l.strip()]
real=[a.strip().lower() for a in open(sys.argv[3]).read().strip().split(',')]
assert real==lines[i], (i,real,lines[i])
EOF
  then pass; else fail "real_hyp.dat wrong"; fi

  name "template.pddl carries <HYPOTHESIS> and no hypothesis machinery"
  if grep -q '<HYPOTHESIS>' "$DS/template.pddl" \
     && ! grep -qE '\(hyp[0-9]+\)' "$DS/template.pddl" \
     && ! grep -q 'total-cost) 0' "$DS/template.pddl"; then pass
  else fail "$(grep -o '(:goal.*' "$DS/template.pddl")"; fi

  name "domain.pddl drops the hypothesis rules and keeps everything else"
  if ! grep -qE ':derived \(hyp[0-9]+\)' "$DS/domain.pddl" \
     && [[ "$(grep -c 'increase (total-cost)' "$DS/domain.pddl")" -ge 8 ]] \
     && grep -q ':action recon' "$DS/domain.pddl"; then pass
  else fail "domain export wrong"; fi

  name "and drops :derived-predicates once no derived section is left"
  # The published source domain declares only what it uses; a stale capability
  # flag is inert but untidy.
  if [[ "$(grep -c '(:derived ' "$DS/domain.pddl")" -eq 0 ]] \
     && ! grep -q ':derived-predicates' "$DS/domain.pddl"; then pass
  else fail "stale :derived-predicates in the exported requirements"; fi

  name "the export re-imports into a working FiFO instance"
  # The round trip: make-recognition-instance.lisp is the reader this inverts.
  { echo "(occur-in-order"; sed 's/^/  /' "$DS/obs.dat"; echo ")"; } > "$DS/ev.txt"
  if sbcl --script "$PR/make-recognition-instance.lisp" \
       "$DS/domain.pddl" "$DS/template.pddl" "$DS/hyps.dat" "$DS/ev.txt" \
       "$TMP/reimport" >"$TMP/reimport.log" 2>&1 \
     && [[ -s "$TMP/reimport/problem.pddl" && -s "$TMP/reimport/domain-costs.pddl" ]]; then pass
  else fail "re-import failed"; tail -3 "$TMP/reimport.log" | sed 's/^/      | /'; fi

  name "the re-imported goal is the hypothesis disjunction again"
  if grep -qE '\(hyp0\)' "$TMP/reimport/problem.pddl" \
     && grep -qE ':derived \(hyp0\)' "$TMP/reimport/domain-costs.pddl"; then pass
  else fail "round trip lost the hypotheses"; fi

  name "the re-import does not double the action costs"
  # add-cost-to-action leaves an action that already has an increase effect alone.
  if [[ "$(grep -c 'increase (total-cost)' "$TMP/reimport/domain-costs.pddl")" \
        -eq "$(grep -c 'increase (total-cost)' "$DS/domain.pddl")" ]]; then pass
  else fail "costs changed across the round trip"; fi

  name "the re-imported instance solves, embedding the observations"
  NOBS=$(grep -c . "$DS/obs.dat")
  if WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$TMP/reimport/problem.pddl" \
       --domain "$TMP/reimport/domain-costs.pddl" --minslices "$((NOBS+1))" --maxslices "$((NOBS+5))" \
       --pddl-evidence-file "$TMP/reimport/evidence-$NOBS.txt" >"$TMP/ri.log" 2>&1 \
     && pycheck "$DS/obs.dat" "$TMP/reimport/problem.answer" <<'EOF'
import sys,re
obs=[l.strip().upper() for l in open(sys.argv[1]) if l.strip()]
ans=open(sys.argv[2]).read()
prev=0
for o in obs:                                  # embedded at increasing slices
    ts=sorted(int(s) for s in re.findall(r'\(OCCURS %s (\d+)\)'%re.escape(o),ans))
    nxt=[t for t in ts if t>prev]
    assert nxt, (o,ts,prev)
    prev=nxt[0]
EOF
  then pass; else fail "re-imported instance did not embed its own observations"
       tail -3 "$TMP/ri.log" | sed 's/^/      | /'; fi

  name "a fluent named in --observe is refused"
  if bash "$EVGEN" --problem "$TMP/problem.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "1-3" --observe "recon,recon-performed" --export-dataset "$TMP/ds2" 2>&1 >/dev/null \
     | grep -q "cannot record the fluent"; then pass
  else fail "obs.dat cannot hold a fluent; should have said so"; fi

  name "--negative-evidence 1 is refused"
  if bash "$EVGEN" --problem "$TMP/problem.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "1-3" --negative-evidence 1 --export-dataset "$TMP/ds2" 2>&1 >/dev/null \
     | grep -q "observed to happen"; then pass
  else fail "should refuse negative evidence"; fi

  name "--export-dataset alone needs no --evidence"
  if bash "$EVGEN" --problem "$TMP/problem.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "1-3" --export-dataset "$TMP/ds3" >/dev/null 2>&1 \
     && [[ -s "$TMP/ds3/obs.dat" ]]; then pass
  else fail "--evidence should be optional here"; fi
else
  echo "  (skipping: could not solve the recognition fixture)"
fi

name "a domain with other derived predicates keeps :derived-predicates"
# The converse of the case above: DerivedPreds defines derived predicates that
# are not hypotheses, so the flag must survive.  Checked on the export function's
# own logic via a synthetic domain, since DerivedPreds is not a recognition
# instance and so cannot be exported end to end.
if pycheck <<'EOF'
import subprocess,os,sys,tempfile,textwrap
repo=os.environ["REPO"]
d=tempfile.mkdtemp()
open(d+"/t.lisp","w").write(textwrap.dedent(f"""
  (load "{repo}/lisp/FiFO.lisp") (load "{repo}/lisp/pddl2fifo.lisp")
  (load "{repo}/SatPlan/evgen.lisp")
  (let ((dom '(define (domain d)
                (:requirements :strips :derived-predicates)
                (:derived (hyp0) (and (p a)))
                (:derived (other) (and (q b)))
                (:action go :parameters () :effect (p a)))))
    (princ (evgen--export-domain dom (list (intern "HYP0")))))
  """))
out=subprocess.run(["sbcl","--noinform","--disable-debugger","--eval",
                    f'(load "{d}/t.lisp")',"--quit"],capture_output=True,text=True).stdout
assert "DERIVED-PREDICATES" in out.upper(), out[-300:]
assert "OTHER" in out.upper(), out[-300:]
assert "HYP0" not in out.upper(), out[-300:]
EOF
then pass; else fail "a non-hypothesis derived predicate lost its requirement flag"; fi

name "a non-recognition problem is refused"
# The clara-logistics fixture has no hypothesis disjunction, so hyps.dat cannot
# be made -- say that rather than write a meaningless dataset.
if everr --slices "2" --export-dataset "$TMP/ds4" | grep -q "needs a recognition instance"
then pass; else fail "should refuse a problem with no hypotheses"; fi

name "neither --evidence nor --export-dataset is an error"
if bash "$EVGEN" --problem "$PROB" --slices "2" 2>&1 >/dev/null | grep -q "nothing to write"
then pass; else fail "should require one of the two outputs"; fi

# ------------------------------------------------ :constraints export ------
# The observations as PDDL 3.0 trajectory constraints at their EXACT slices.
# FiFO reads this dialect, so unlike the dataset export it can be checked by
# solving the exported problem, which is the test that matters: the constraints
# must actually bind.

echo
echo "=== --export-constraints (PDDL 3.0 trajectory constraints) ==="
XC="$TMP/xc"

if [[ "$RSOLVED" -eq 1 ]]; then
  bash "$EVGEN" --problem "$TMP/sg.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "1-3" --export-constraints "$XC" >/dev/null 2>&1

  name "writes domain.pddl, problem.pddl and a README"
  if [[ -s "$XC/domain.pddl" && -s "$XC/problem.pddl" && -s "$XC/README.md" ]]; then pass
  else fail "missing files"; fi

  name "constraints are exactly the solution's literals at those slices"
  if pycheck "$TMP/sg.answer" "$XC/problem.pddl" <<'EOF'
import sys,re
ans=open(sys.argv[1]).read(); prob=open(sys.argv[2]).read()
sec=prob.split('(:constraints')[1].split('(:goal')[0]
got=set()
for op,t1,t2,term in re.findall(r'\((hold-during|occur-sometime) (\d+) (\d+) (\([^)]*\))',sec):
    assert t1==t2, (op,t1,t2)          # an observation is a point, not a window
    got.add((op,int(t1),term.lower()))
want=set()
for kind,term,s in re.findall(r'\((HOLDS|OCCURS) (\([^)]*\)) (\d+)\)',ans):
    if int(s) in (1,2,3):
        op='hold-during' if kind=='HOLDS' else 'occur-sometime'
        want.add((op,int(s),term.lower()))
assert got==want, ("missing",sorted(want-got)[:2],"extra",sorted(got-want)[:2])
EOF
  then pass; else fail "constraint set does not match the solution"; fi

  name "the exported problem solves at the source plan's cost"
  # The constraints must be satisfiable by the very plan they came from.
  SRCCOST=$(grep -oE '\(\*OBJECTIVE\* [0-9]+\)' "$TMP/sg.answer" | grep -oE '[0-9]+')
  XCOST=$(WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$XC/problem.pddl" \
            --domain "$XC/domain.pddl" --numslices 6 2>&1 \
          | grep -oE 'cost [0-9]+' | tail -1 | grep -oE '[0-9]+')
  if [[ -n "$XCOST" && "$XCOST" == "$SRCCOST" ]]; then pass
  else fail "exported cost '$XCOST' vs source '$SRCCOST'"; fi

  name "and they BIND: a constraint moved to another slice breaks it"
  sed 's/(occur-sometime 3 3 (gain-root leo))/(occur-sometime 1 1 (gain-root leo))/' \
      "$XC/problem.pddl" > "$XC/bad.pddl"
  BADOUT=$(WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$XC/bad.pddl" \
             --domain "$XC/domain.pddl" --numslices 6 2>&1)
  BADCOST=$(echo "$BADOUT" | grep -oE 'cost [0-9]+' | tail -1 | grep -oE '[0-9]+')
  if echo "$BADOUT" | grep -qi unsatisfiable || [[ -n "$BADCOST" && "$BADCOST" -gt "$SRCCOST" ]]
  then pass; else fail "a wrong-slice constraint changed nothing (cost $BADCOST)"; fi

  name ":constraints is added to the domain's requirements, once"
  if grep -q ':constraints' "$XC/domain.pddl" \
     && [[ "$(grep -o ':constraints' "$XC/domain.pddl" | wc -l | tr -d ' ')" -eq 1 ]]; then pass
  else fail "requirements wrong"; fi

  name "an action observation carries the occur-sometime caveat"
  if grep -q 'occur-sometime' "$XC/problem.pddl" \
     && head -6 "$XC/problem.pddl" | grep -q 'NOT part of' \
     && grep -q 'must support it' "$XC/problem.pddl"; then pass
  else fail "no portability note beside the non-standard operator"; fi

  name "a fluents-only export is standard PDDL 3.0, with no caveat"
  bash "$EVGEN" --problem "$TMP/sg.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "2-3" \
       --observe "recon-performed,access-obtained" --export-constraints "$TMP/xf" >/dev/null 2>&1
  if [[ "$(grep -c 'occur-sometime' "$TMP/xf/problem.pddl")" -eq 0 ]] \
     && ! grep -q 'NOT part of' "$TMP/xf/problem.pddl" \
     && grep -q 'No extension is needed' "$TMP/xf/README.md" \
     && grep -q 'hold-during' "$TMP/xf/problem.pddl"; then pass
  else fail "fluents-only export still looks non-standard"; fi

  name "the goal and everything else are left alone"
  if grep -q '(:goal (hyp3))' "$XC/problem.pddl" \
     && grep -q '(:init (dummy)' "$XC/problem.pddl"; then pass
  else fail "the export changed more than the constraints"; fi

  name "--negative-evidence 1 is refused"
  if bash "$EVGEN" --problem "$TMP/sg.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "2" --negative-evidence 1 \
       --export-constraints "$TMP/xn" 2>&1 >/dev/null \
     | grep -q "did NOT occur"; then pass
  else fail "should refuse: no constraint says an action did not occur"; fi

  name "--export-constraints alone needs no --evidence"
  if bash "$EVGEN" --problem "$TMP/sg.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "2" --export-constraints "$TMP/xa" >/dev/null 2>&1 \
     && [[ -s "$TMP/xa/problem.pddl" ]]; then pass
  else fail "--evidence should be optional here"; fi
else
  echo "  (skipping: could not solve the recognition fixture)"
fi

  name "all three outputs can be written in one run"
  # satplan.md says so; the counts differ legitimately, since obs.dat is
  # actions-only while the other two carry fluents too.
  rm -rf "$TMP/all3"
  if bash "$EVGEN" --problem "$TMP/problem.pddl" --domain "$TMP/intrusion-detection-costs.pddl" \
       --solution "$TMP/sg.answer" --slices "1-2" \
       --evidence "$TMP/all3/ev.txt" --recognition 1 \
       --export-dataset "$TMP/all3/ds" --export-constraints "$TMP/all3/xc" >/dev/null 2>&1 \
     && [[ -s "$TMP/all3/ev.txt" && -s "$TMP/all3/ds/obs.dat" && -s "$TMP/all3/xc/problem.pddl" ]]
  then pass; else fail "the three outputs do not combine"; fi

name "it works on a plain problem, with no hypotheses needed"
# Unlike --export-dataset, this needs no recognition instance.
if ev --evidence "$TMP/ignore.txt" --slices "2" --export-constraints "$TMP/xp" >/dev/null 2>&1 \
   && grep -q '(:constraints' "$TMP/xp/problem.pddl"; then pass
else fail "should export any solved problem"; fi

# --------------------------------------------------------------- errors ----

err() { name "$1"; shift; local want="$1"; shift
        local got; got="$(everr "$@")"
        if echo "$got" | grep -qi -- "$want"; then pass; else fail "got: $got"; fi; }

err "a slice past the horizon is refused" "beyond the solution's horizon" \
    --evidence "$TMP/x.txt" --slices "1-3,$((HORIZON+3))"
err "slice 0 is refused"                "numbered from 1" \
    --evidence "$TMP/x.txt" --slices "0"
err "a backwards range is refused"      "backwards" \
    --evidence "$TMP/x.txt" --slices "3-1"
err "a stray comma is refused"          "stray comma" \
    --evidence "$TMP/x.txt" --slices "1,,3"
err "a non-numeric slice is refused"    "not a slice number" \
    --evidence "$TMP/x.txt" --slices "abc"
err "an unknown --observe name is refused" "not a fluent or action" \
    --evidence "$TMP/x.txt" --slices "1-3" --observe "flyy"
err "an unknown name beside a known one is still refused" "not a fluent or action" \
    --evidence "$TMP/x.txt" --slices "1-3" --observe "at,flyy"
err "--negative-evidence 2 is refused"  "must be 0 or 1" \
    --evidence "$TMP/x.txt" --slices "1-3" --negative-evidence 2
err "an empty selection is refused, not written" "no observations selected" \
    --evidence "$TMP/x.txt" --slices "$HORIZON" --observe "fly"
name "a missing solution file is reported"
if bash "$EVGEN" --problem "$PROB" --domain "$DOMAIN" --evidence "$TMP/x.txt" \
     --slices "2" --solution "$TMP/nope.answer" 2>&1 >/dev/null \
   | grep -q "solution file not found"; then pass
else fail "should report a missing solution"; fi
err "an unknown flag is reported"       "unknown option" \
    --evidence "$TMP/x.txt" --slices "2" --bogus 1

name "a refused run leaves no evidence file behind"
rm -f "$TMP/x.txt"
everr --evidence "$TMP/x.txt" --slices "1-3" --observe "flyy" >/dev/null
if [[ ! -e "$TMP/x.txt" ]]; then pass; else fail "wrote a file despite erroring"; fi

name "an UNSAT solution file is refused"
printf 'UNSAT\n' > "$TMP/unsat.answer"
if bash "$EVGEN" --problem "$PROB" --domain "$DOMAIN" --evidence "$TMP/x.txt" \
     --slices "2" --solution "$TMP/unsat.answer" 2>&1 >/dev/null \
   | grep -q "not SAT"; then pass; else fail "accepted a solution with no plan"; fi

name "missing --evidence AND --export-dataset is reported"
if bash "$EVGEN" --problem "$PROB" --slices "2" 2>&1 >/dev/null | grep -q "nothing to write"
then pass; else fail "should require one of the two outputs"; fi

name "missing --slices is reported"
if bash "$EVGEN" --problem "$PROB" --evidence "$TMP/x.txt" 2>&1 >/dev/null | grep -q "slices is required"
then pass; else fail "should require --slices"; fi

name "a missing problem file is reported"
if bash "$EVGEN" --problem "$TMP/nope.pddl" --evidence "$TMP/x.txt" --slices "2" 2>&1 >/dev/null \
   | grep -q "problem file not found"; then pass; else fail "should reject a missing problem"; fi

echo
echo "=== summary: $PASS passed, $FAIL failed ==="
[[ $FAIL -eq 0 ]]
