#!/bin/bash
#
# run-test-evgen.sh -- regression tests for SatPlan/evgen.sh, the plan-recognition
# evidence generator.
#
# Behavioral, not gold diffs: the fixture problem is generated by ppgen.sh from a
# fixed seed and solved by planner.sh, so what is asserted is the relationship
# between the solution and the evidence -- the emitted literals are exactly the
# true ones at the requested slices, negatives complete the partition, and the
# file actually binds when handed back to the planner.
#
# That last one matters most.  Slice-pinned evidence fails SILENTLY downstream:
# an out-of-range slice or a misspelled predicate becomes a fresh unconstrained
# atom and the planner returns its UNCONDITIONED answer, no error.  So the suite
# checks not only that evgen refuses to write such a literal, but that a correct
# file changes the answer when it should.
#
# Run from anywhere:  bash tests/run-test-evgen.sh
# The cases that solve need a MaxSAT solver and skip cleanly without one.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd -P)"
export FIFO_LISP="${FIFO_LISP:-$REPO/lisp}"
EVGEN="$REPO/SatPlan/evgen.sh"
PPGEN="$REPO/SatPlan/ppgen.sh"
PLANNER="$REPO/bin/planner.sh"
DOMAIN="$REPO/SatPlan/clara-logistics.pddl"
SOLVER="${WEIGHTED_SOLVER:-EvalMaxSAT_bin}"
TMP="$(mktemp -d)"; TMP="$(cd "$TMP" && pwd -P)"
trap 'rm -rf "$TMP"' EXIT

command -v sbcl >/dev/null 2>&1 || { echo "sbcl not found on PATH" >&2; exit 2; }

PASS=0; FAIL=0
name() { printf '  %-56s ... ' "$1"; }
pass() { echo "PASS"; PASS=$((PASS+1)); }
fail() { echo "FAIL ($1)"; FAIL=$((FAIL+1)); }
pycheck() { python3 - "$@"; }

ev()    { bash "$EVGEN" --problem "$PROB" --domain "$DOMAIN" "$@" 2>/dev/null; }
everr() { bash "$EVGEN" --problem "$PROB" --domain "$DOMAIN" "$@" 2>&1 >/dev/null \
            | grep -v 'STYLE-WARNING\|^;\|^$' | tr '\n' ' '; }

# ---------------------------------------------------------------- fixture ---

PROB="$TMP/pb.pddl"
bash "$PPGEN" --style clique --clique-size 3 --number-cliques 2 --packages 3 \
     --trucks 2 --airplanes 1 --preferences 1 6 --goals-per-package 2 1 \
     --seed 23 -o "$PROB" 2>/dev/null
ANSWER="$TMP/pb.answer"

if command -v "$SOLVER" >/dev/null 2>&1; then
  WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$PROB" --domain "$DOMAIN" \
      --maxslices 12 >"$TMP/plan.log" 2>&1
fi
if [[ ! -f "$ANSWER" ]]; then
  echo "  (skipping: could not solve the fixture problem -- no MaxSAT solver '$SOLVER'?)"
  echo
  echo "=== summary: 0 passed, 0 failed (skipped) ==="
  exit 0
fi
HORIZON=$(grep -oE '\) [0-9]+\)$' "$ANSWER" | grep -oE '[0-9]+' | sort -n | tail -1)
BASE_COST=$(grep -oE '\(\*OBJECTIVE\* [0-9]+\)' "$ANSWER" | grep -oE '[0-9]+')

echo "=== evgen.sh (fixture: horizon $HORIZON, cost $BASE_COST) ==="

# ------------------------------------------------------------ positives ----

name "emits exactly the true literals at the requested slices"
ev --evidence "$TMP/a.txt" --slices "1-3,5" >/dev/null
if pycheck "$ANSWER" "$TMP/a.txt" <<'EOF'
import sys,re
ans=open(sys.argv[1]).read(); ev=open(sys.argv[2]).read()
want=set()
for kind,term,s in re.findall(r'\((HOLDS|OCCURS) (\([^)]*\)) (\d+)\)',ans):
    if int(s) in (1,2,3,5): want.add((kind.lower(),term.lower(),s))
got=set()
for kind,term,s in re.findall(r'^\((holds|occurs) (\([^)]*\)) (\d+)\)',ev,re.M):
    got.add((kind,term,s))
assert got==want, ("missing",sorted(want-got)[:3],"extra",sorted(got-want)[:3])
assert got, "nothing emitted"
EOF
then pass; else fail "positives do not match the solution"; fi

name "only the requested slices appear"
if pycheck "$TMP/a.txt" <<'EOF'
import sys,re
ev=open(sys.argv[1]).read()
sl={int(s) for s in re.findall(r'^\((?:holds|occurs) \([^)]*\) (\d+)\)',ev,re.M)}
assert sl=={1,2,3,5}, sl
EOF
then pass; else fail "wrong slices"; fi

name "a single slice, and a range, agree with the union of both"
ev --evidence "$TMP/s1.txt" --slices "2" >/dev/null
ev --evidence "$TMP/s2.txt" --slices "3" >/dev/null
ev --evidence "$TMP/s12.txt" --slices "2-3" >/dev/null
if [[ "$(grep -c '^(' "$TMP/s1.txt")" -gt 0 ]] && \
   [[ $(( $(grep -c '^(' "$TMP/s1.txt") + $(grep -c '^(' "$TMP/s2.txt") )) \
      -eq "$(grep -c '^(' "$TMP/s12.txt")" ]]
then pass; else fail "a range is not the union of its slices"; fi

# -------------------------------------------------------------- observe ----

name "--observe restricts to those fluent and action names"
ev --evidence "$TMP/o.txt" --slices "2-4" --observe "fly,in" >/dev/null
if pycheck "$TMP/o.txt" <<'EOF'
import sys,re
ev=open(sys.argv[1]).read()
heads={t.split()[0].lstrip('(') for t in
       re.findall(r'^\((?:holds|occurs) (\([^)]*\)) \d+\)',ev,re.M)}
assert heads<= {'fly','in'} and heads, heads
EOF
then pass; else fail "restriction wrong"; fi

name "--observe mixes a fluent name and an action name"
if grep -q '^(holds (in ' "$TMP/o.txt" && grep -q '^(occurs (fly ' "$TMP/o.txt"
then pass; else fail "the spec's \"fly,in\" case lost one of the two"; fi

name "no --observe means no restriction"
if pycheck "$TMP/a.txt" <<'EOF'
import sys,re
heads={t.split()[0].lstrip('(') for t in
       re.findall(r'^\((?:holds|occurs) (\([^)]*\)) \d+\)',open(sys.argv[1]).read(),re.M)}
assert len(heads)>2, heads
EOF
then pass; else fail "unrestricted run looks restricted"; fi

# --------------------------------------------------------- slice ranges ----

name "the last slice yields fluents but no actions"
ev --evidence "$TMP/last.txt" --slices "$HORIZON" >/dev/null
if [[ "$(grep -c '^(holds' "$TMP/last.txt")" -gt 0 && \
      "$(grep -c '^(occurs' "$TMP/last.txt" || true)" -eq 0 ]]
then pass; else fail "actions run 1..N-1, so slice N should have none"; fi

name "the last slice has no actions under --negative-evidence either"
# The positives-only case cannot see this: nothing is true at slice N anyway, so
# an emitter that forgot the actslices bound would look identical.  Negatives
# make it visible -- every ground action would show up as (not (occurs ... N)).
ev --evidence "$TMP/lastn.txt" --slices "$HORIZON" --negative-evidence 1 >/dev/null
if [[ "$(grep -c 'occurs' "$TMP/lastn.txt" || true)" -eq 0 && \
      "$(grep -c '^(not (holds' "$TMP/lastn.txt")" -gt 0 ]]
then pass; else fail "actions appeared at slice N (actions run 1..N-1)"; fi

name "the slice before it has both"
ev --evidence "$TMP/prev.txt" --slices "$((HORIZON-1))" >/dev/null
if [[ "$(grep -c '^(holds' "$TMP/prev.txt")" -gt 0 && \
      "$(grep -c '^(occurs' "$TMP/prev.txt")" -gt 0 ]]
then pass; else fail "slice N-1 should carry actions"; fi

# ---------------------------------------------------- negative evidence ----

name "--negative-evidence partitions the restricted universe exactly"
ev --evidence "$TMP/n.txt" --slices "3" --observe "in,fly" --negative-evidence 1 >/dev/null
if pycheck "$TMP/n.txt" "$ANSWER" <<'EOF'
import sys,re
ev=open(sys.argv[1]).read(); ans=open(sys.argv[2]).read()
pos={(k,t) for k,t,s in re.findall(r'^\((holds|occurs) (\([^)]*\)) (\d+)\)',ev,re.M)}
neg={(k,t) for k,t,s in re.findall(r'^\(not \((holds|occurs) (\([^)]*\)) (\d+)\)\)',ev,re.M)}
assert pos and neg, (len(pos),len(neg))
assert not (pos & neg), "an atom appears with both polarities"
# every positive is true in the solution, every negative is not
true={(k.lower(),t.lower()) for k,t,s in
      re.findall(r'\((HOLDS|OCCURS) (\([^)]*\)) (\d+)\)',ans) if s=='3'}
assert pos <= true, sorted(pos-true)[:3]
assert not (neg & true), sorted(neg & true)[:3]
EOF
then pass; else fail "positives and negatives do not partition cleanly"; fi

name "--negative-evidence unrestricted covers the whole universe"
ev --evidence "$TMP/nu.txt" --slices "3" --negative-evidence 1 >/dev/null
# the universe at one slice is every ground fluent plus every ground action
if [[ "$(grep -c '^(' "$TMP/nu.txt")" -gt $(( $(grep -c '^(' "$TMP/n.txt") * 5 )) ]]
then pass; else fail "unrestricted negatives are not much larger than the restricted ones"; fi

name "--negative-evidence 0 is the default and emits no negatives"
if ! grep -q '^(not ' "$TMP/a.txt"; then pass
else fail "negatives appeared without the flag"; fi

# ------------------------------------------------------- recorded header ---

name "the header records every setting, defaults included"
if pycheck "$TMP/a.txt" <<'EOF'
import sys,re
p=dict(re.findall(r'^;;   (--[\w-]+) (.+)$',open(sys.argv[1]).read(),re.M))
for f in ('--problem','--evidence','--solution','--domain','--slices',
          '--observe','--negative-evidence'):
    assert f in p, (f,p)
assert p['--slices']=='1-3,5' and p['--negative-evidence']=='0' and p['--observe']=='""'
EOF
then pass; else fail "settings block incomplete"; fi

name "the header names the solution horizon and the literal count"
if grep -qE "^;; Solution horizon: $HORIZON slices \(fluents 1-$HORIZON, actions 1-$((HORIZON-1))\); [0-9]+ literals\.$" "$TMP/a.txt"
then pass; else fail "$(grep '^;; Solution' "$TMP/a.txt")"; fi

name "the recorded settings block replays byte for byte"
RT_BAD=""
for spec in "--slices 1-3,5" \
            "--slices 2-4 --observe fly,in" \
            "--slices 3 --observe in,fly --negative-evidence 1"; do
  ev --evidence "$TMP/rt.txt" $spec >/dev/null
  cp "$TMP/rt.txt" "$TMP/rt-orig.txt"
  # feed the file's own header back in as the command line; it names --evidence,
  # so this rewrites the same file and must reproduce it exactly
  eval "bash '$EVGEN' $(sed -n 's/^;;   //p' "$TMP/rt.txt" | tr '\n' ' ')" 2>/dev/null
  diff -q "$TMP/rt-orig.txt" "$TMP/rt.txt" >/dev/null || { RT_BAD="$spec"; break; }
done
if [[ -z "$RT_BAD" ]]; then pass; else fail "did not replay: $RT_BAD"; fi

# ------------------------------------------------------------ defaults -----

name "--solution defaults to <problem>.answer"
ev --evidence "$TMP/d.txt" --slices "2" >/dev/null
if grep -q ";;   --solution .*pb\.answer$" "$TMP/d.txt"; then pass
else fail "default solution path wrong"; fi

name "--domain defaults to the problem's own (:domain ...)"
cp "$DOMAIN" "$TMP/clara-logistics.pddl"
if bash "$EVGEN" --problem "$PROB" --evidence "$TMP/dd.txt" --slices "2" 2>/dev/null \
   && grep -q '^(holds' "$TMP/dd.txt"
then pass; else fail "did not resolve the domain beside the problem"; fi

# -------------------------------------------------------------- binding ----

name "the evidence binds: the true observations reproduce the plan's cost"
run_cost() {  # run_cost <evidence-file>
  WEIGHTED_SOLVER="$SOLVER" bash "$PLANNER" "$PROB" --domain "$DOMAIN" \
      --numslices "$HORIZON" --evidence-file "$1" 2>&1 \
    | grep -oE 'cost [0-9]+' | tail -1 | grep -oE '[0-9]+'
}
if [[ "$(run_cost "$TMP/a.txt")" == "$BASE_COST" ]]; then pass
else fail "conditioning on the real plan changed its cost"; fi

name "the evidence binds: a shifted observation costs more"
# move one observed action to a different slice; the plan must now work around it
python3 - "$TMP/o.txt" "$TMP/bad.txt" <<'EOF'
import sys,re
t=open(sys.argv[1]).read()
m=re.search(r'^\(occurs (\([^)]*\)) (\d+)\)$',t,re.M)
assert m, "fixture has no observed action to shift"
t=t.replace(m.group(0), "(occurs %s 1)" % m.group(1), 1)
open(sys.argv[2],'w').write(t)
EOF
BAD_COST="$(run_cost "$TMP/bad.txt")"
if [[ -n "$BAD_COST" && "$BAD_COST" -gt "$BASE_COST" ]]; then pass
else fail "shifted observation gave cost '$BAD_COST' vs base $BASE_COST"; fi

# --------------------------------------------------------------- errors ----

err() { name "$1"; shift; local want="$1"; shift
        local got; got="$(everr "$@")"
        if echo "$got" | grep -qi -- "$want"; then pass; else fail "got: $got"; fi; }

err "a slice past the horizon is refused" "beyond the solution's horizon" \
    --evidence "$TMP/x.txt" --slices "1-3,$((HORIZON+3))"
err "slice 0 is refused"                "numbered from 1" \
    --evidence "$TMP/x.txt" --slices "0"
err "a backwards range is refused"      "backwards" \
    --evidence "$TMP/x.txt" --slices "3-1"
err "a stray comma is refused"          "stray comma" \
    --evidence "$TMP/x.txt" --slices "1,,3"
err "a non-numeric slice is refused"    "not a slice number" \
    --evidence "$TMP/x.txt" --slices "abc"
err "an unknown --observe name is refused" "not a fluent or action" \
    --evidence "$TMP/x.txt" --slices "1-3" --observe "flyy"
err "an unknown name beside a known one is still refused" "not a fluent or action" \
    --evidence "$TMP/x.txt" --slices "1-3" --observe "at,flyy"
err "--negative-evidence 2 is refused"  "must be 0 or 1" \
    --evidence "$TMP/x.txt" --slices "1-3" --negative-evidence 2
err "an empty selection is refused, not written" "no observations selected" \
    --evidence "$TMP/x.txt" --slices "$HORIZON" --observe "fly"
err "a missing solution file is reported" "solution file not found" \
    --evidence "$TMP/x.txt" --slices "2" --solution "$TMP/nope.answer"
err "an unknown flag is reported"       "unknown option" \
    --evidence "$TMP/x.txt" --slices "2" --bogus 1

name "a refused run leaves no evidence file behind"
rm -f "$TMP/x.txt"
everr --evidence "$TMP/x.txt" --slices "1-3" --observe "flyy" >/dev/null
if [[ ! -e "$TMP/x.txt" ]]; then pass; else fail "wrote a file despite erroring"; fi

name "an UNSAT solution file is refused"
printf 'UNSAT\n' > "$TMP/unsat.answer"
if everr --evidence "$TMP/x.txt" --slices "2" --solution "$TMP/unsat.answer" \
   | grep -q "not SAT"; then pass; else fail "accepted a solution with no plan"; fi

name "missing --evidence is reported"
if bash "$EVGEN" --problem "$PROB" --slices "2" 2>&1 >/dev/null | grep -q "evidence is required"
then pass; else fail "should require --evidence"; fi

name "missing --slices is reported"
if bash "$EVGEN" --problem "$PROB" --evidence "$TMP/x.txt" 2>&1 >/dev/null | grep -q "slices is required"
then pass; else fail "should require --slices"; fi

name "a missing problem file is reported"
if bash "$EVGEN" --problem "$TMP/nope.pddl" --evidence "$TMP/x.txt" --slices "2" 2>&1 >/dev/null \
   | grep -q "problem file not found"; then pass; else fail "should reject a missing problem"; fi

echo
echo "=== summary: $PASS passed, $FAIL failed ==="
[[ $FAIL -eq 0 ]]
