;; Generated by make-recognition-instance.lisp from IntrusionDetection/template.pddl:
;; the goal is the disjunction of all 10 candidate goals in IntrusionDetection/hyps.dat.
(define (problem intrusion-detection-10-hosts) (:domain intrusion-detection)
 (:objects perseus cassiopea andromeda sagittarius scorpio virgo aries leo
  libra taurus - host)
 (:init (dummy) (= (total-cost) 0))
 (:goal
  (or (hyp0) (hyp1) (hyp2) (hyp3) (hyp4) (hyp5) (hyp6) (hyp7) (hyp8) (hyp9))))
