;; Generated by make-recognition-instance.lisp from IntrusionDetection/template.pddl:
;; the goal is the disjunction of all 10 candidate goals in IntrusionDetection/hyps.dat.
(define (problem intrusion-detection-10-hosts) (:domain intrusion-detection)
 (:objects perseus cassiopea andromeda sagittarius scorpio virgo aries leo
  libra taurus - host)
 (:init (dummy) (= (total-cost) 0))
 (:goal
  (or
   (and (information-gathered perseus) (information-gathered cassiopea)
        (information-gathered andromeda) (information-gathered sagittarius)
        (information-gathered scorpio) (information-gathered virgo)
        (information-gathered aries) (information-gathered leo)
        (information-gathered libra) (information-gathered taurus))
   (and (data-stolen-from perseus) (data-stolen-from taurus)
        (data-stolen-from aries))
   (and (vandalized perseus) (vandalized taurus) (vandalized leo))
   (and (data-stolen-from leo) (data-stolen-from taurus) (vandalized taurus))
   (and (vandalized virgo) (data-stolen-from aries)
        (data-stolen-from sagittarius))
   (and (data-stolen-from cassiopea) (data-stolen-from libra)
        (vandalized taurus))
   (and (vandalized libra) (vandalized virgo) (vandalized scorpio))
   (and (data-stolen-from andromeda) (vandalized virgo)
        (data-stolen-from aries))
   (and (vandalized sagittarius) (vandalized scorpio)
        (data-stolen-from virgo))
   (and (data-stolen-from perseus) (data-stolen-from cassiopea)
        (vandalized libra)))))
