(define (domain blocks-dp)
  (:requirements :strips :typing :derived-predicates :disjunctive-preconditions)
  (:predicates (on ?x ?y - block) (ontable ?x - block) (clear ?x - block)
               (handempty) (holding ?x - block))
  ;; parameterized derived predicate with a quantified body
  (:derived (clear-d ?x - block)
     (forall (?y - block) (not (on ?y ?x))))
  ;; nullary derived predicate equal to a conjunction (marginal-readout case)
  (:derived (spells-ab)
     (and (on a b) (ontable b) (clear-d a)))
  (:action pick-up :parameters (?x - block)
     :precondition (and (clear ?x) (ontable ?x) (handempty))
     :effect (and (not (ontable ?x)) (not (clear ?x)) (not (handempty)) (holding ?x)))
  (:action put-down :parameters (?x - block)
     :precondition (holding ?x)
     :effect (and (not (holding ?x)) (clear ?x) (handempty) (ontable ?x)))
  (:action stack :parameters (?x ?y - block)
     :precondition (and (holding ?x) (clear ?y))
     :effect (and (not (holding ?x)) (not (clear ?y)) (clear ?x) (handempty) (on ?x ?y)))
  (:action unstack :parameters (?x ?y - block)
     :precondition (and (on ?x ?y) (clear ?x) (handempty))
     :effect (and (holding ?x) (clear ?y) (not (clear ?x)) (not (handempty)) (not (on ?x ?y)))))
