;; Generated by make-recognition-instance.lisp from BlockWords/block-words.pddl:
;; uniform action cost 1 (Boltzmann model: each action
;; multiplies a trajectory's probability by exp(-1/scale)).
(define (domain blocks)
 (:requirements :strips :typing :action-costs :disjunctive-preconditions)
 (:functions (total-cost)) (:types block)
 (:predicates (on ?x ?y - block) (ontable ?x - block) (clear ?x - block)
  (handempty) (holding ?x - block))
 (:action pick-up :parameters (?x - block) :precondition
  (and (clear ?x) (ontable ?x) (handempty)) :effect
  (and (not (ontable ?x)) (not (clear ?x)) (not (handempty)) (holding ?x)
       (increase (total-cost) 1)))
 (:action put-down :parameters (?x - block) :precondition (holding ?x)
  :effect
  (and (not (holding ?x)) (clear ?x) (handempty) (ontable ?x)
       (increase (total-cost) 1)))
 (:action stack :parameters (?x ?y - block) :precondition
  (and (holding ?x) (clear ?y)) :effect
  (and (not (holding ?x)) (not (clear ?y)) (clear ?x) (handempty) (on ?x ?y)
       (increase (total-cost) 1)))
 (:action unstack :parameters (?x ?y - block) :precondition
  (and (on ?x ?y) (clear ?x) (handempty)) :effect
  (and (holding ?x) (clear ?y) (not (clear ?x)) (not (handempty))
       (not (on ?x ?y)) (increase (total-cost) 1))))
