;; Generated by make-recognition-instance.lisp from BlockWords/template.pddl:
;; the goal is the disjunction of all 21 candidate goals in BlockWords/hyps.dat.
(define (problem blocks_words) (:domain blocks)
 (:objects d r a w o e p c - block)
 (:init (handempty) (clear o) (ontable o) (clear r) (on r p) (ontable p)
  (clear e) (ontable e) (clear d) (on d a) (on a c) (ontable c) (clear w)
  (ontable w) (= (total-cost) 0))
 (:goal
  (or (hyp0) (hyp1) (hyp2) (hyp3) (hyp4) (hyp5) (hyp6) (hyp7) (hyp8) (hyp9)
      (hyp10) (hyp11) (hyp12) (hyp13) (hyp14) (hyp15) (hyp16) (hyp17) (hyp18)
      (hyp19) (hyp20))))
